### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by twanc** [jpts/kubectl-execws#2]
Hello, i am having below issue

panic: assignment to entry in nil map

goroutine 1 [running]:
net/textproto.MIMEHeader.Set(...)
	/usr/local/Cellar/go/1.17.5/libexec/src/net/textproto/header.go:22
net/http.Header.Set(...)
	/usr/local/Cellar/go/1.17.5/libexec/src/net/http/header.go:38
k8s.io/client-go/plugin/pkg/client/auth/exec.(*roundTripper).RoundTrip(0xc00052a1c8, 0xc000275400)
	/Users/twanc/go/pkg/mod/k8s.io/client-go@v0.21.8/plugin/pkg/client/auth/exec/exec.go:310 +0x18d
github.com/jpts/kubectl-execws/cmd.doExec(0xc0000f7d60)
	/Users/twanc/Tests/kubectl-execws/cmd/exec.go:155 +0x12c
github.com/jpts/kubectl-execws/cmd.glob..func1(0x1aa1400, {0xc00008af80, 0x2, 0x4})
	/Users/twanc/Tests/kubectl-execws/cmd/root.go:59 +0x2be
github.com/spf13/cobra.(*Command).execute(0x1aa1400, {0xc0000200b0, 0x4, 0x4})
	/Users/twanc/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1aa1400)
	/Users/twanc/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/twanc/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/jpts/kubectl-execws/cmd.Execute()
	/Users/twanc/Tests/kubectl-execws/cmd/root.go:69 +0x25
main.main()
	/Users/twanc/Tests/kubectl-execws/main.go:6 +0x17

Any ideas whats wrong?
Thanks

**Comment by twanc** [comment]
The problem is with specific settings of aws config, AWS implementation
